/**
 * The three generated reference pages: their prose, their tables, and their provenance.
 *
 * Nothing here reaches for a file — {@link buildPages} is handed the data and returns
 * `{ path, markdown }`, so the same function serves both the write mode and the drift check.
 * Every count in the prose is computed from that data rather than typed, for the reason
 * `commands/catalogue.ts`'s own header gives: a number in a sentence that nobody can execute is a
 * number that goes wrong.
 */

import { createHash } from 'node:crypto';

import { byGroup, commandRows, paletteActionRows, surfaceShortcutRows } from './command-model.mjs';
import {
  callout,
  cell,
  claimsTable,
  frontmatter,
  keystrokes,
  paragraph,
  table,
} from './markdown.mjs';

/** The renderer files the command pages are derived from, for their provenance blocks. */
const COMMAND_SOURCES = [
  'packages/renderer/src/commands/catalogue.ts',
  'packages/renderer/src/features/command-palette/palette-actions.ts',
  'packages/renderer/src/utils/platform.ts',
  'packages/renderer/src/shell/status-bar.tsx',
];

const VENDOR_SOURCE = 'packages/shared/src/config/ai-vendors.json';

/** Where the generated pages live, relative to `src/content/docs/`. */
export const GENERATED_PAGES = {
  shortcuts: 'reference/keyboard-shortcuts.md',
  commands: 'reference/commands.md',
  aiProviders: 'reference/ai-providers.md',
};

/**
 * The committed screenshots a generated page embeds, as finished Markdown.
 *
 * These are the ONLY part of a generated page that is not derived from the app's source: the
 * images come from `docs-site/src/assets/screenshots/` (captured by `pnpm run docs:shots`, declared
 * in `tests/docs-shots/catalogue.ts`), and the catalogue already maps each shot to the pages that
 * want it. They live here rather than in the pages because these two files are generated and must
 * not be hand-edited — J-99 Phase 3.
 *
 * Paths are relative to `src/content/docs/reference/`, which is where both pages are written.
 */
const SHOT = {
  keyboardShortcuts:
    '![The keyboard shortcuts sheet in the app: bindings in two columns under group headings such as File and tabs, Query, Editor and View, each row giving a command name, its source — Menu, App or Editor — and its keystroke.](../../../assets/screenshots/keyboard-shortcuts-dark.png)',
  aiSetup:
    '![The AI setup dialog: a provider picker, an API key field with Save key beneath it, a preferred-model picker, a "Use this provider" switch, and the AI features switches below a divider.](../../../assets/screenshots/ai-setup-dark.png)',
};

/** A short, stable digest of exactly the data a page renders. */
function digest(data) {
  return createHash('sha256').update(JSON.stringify(data)).digest('hex').slice(0, 12);
}

/** The banner every generated page opens with. */
function generatedBanner() {
  return callout(
    "**Generated page** — every table below is read out of the app's own source when this site is",
    'built. Do not edit this file by hand: `pnpm run check` and `pnpm run build` regenerate it and',
    'fail when what is committed here disagrees with the source.'
  );
}

/** How the command pages get their data — the part a reader might not believe without being told. */
const COMMAND_MECHANISM = paragraph(
  'It does not import the renderer. Each module is compiled with the TypeScript compiler and run',
  'inside an isolated `node:vm` context whose module resolver is declared up front: the files it',
  'may reach are resolved for real, `lucide-react` resolves to an inert marker, and anything else',
  "throws rather than pulling the app's dependency tree into the docs build. The command table is",
  'loaded twice, once with a macOS user agent and once with a Windows one, so both keystroke',
  "columns come from the app's own formatter rather than from a second table kept here."
);

/** The same, for the page that reads one JSON file. */
const VENDOR_MECHANISM = paragraph(
  'That is the same file the app loads at startup. The generator asserts its shape before',
  'rendering anything, so a restructured configuration fails the docs build rather than emitting',
  'an empty table.'
);

/** The provenance section: what was read, what came out, and how to regenerate it. */
function provenance(sources, mechanism, dataDigest) {
  return [
    '## How this page is generated',
    '',
    '`docs-site/scripts/generate-reference.mjs` reads these files and writes this page:',
    '',
    sources.map(source => `- \`${source}\``).join('\n'),
    '',
    mechanism,
    '',
    paragraph(
      `Data digest: \`${dataDigest}\` — a fingerprint of exactly the values rendered above. It`,
      'changes when what the app ships changes, and not when an unrelated comment in one of those',
      'files does.'
    ),
    '',
    'Regenerate from `docs-site/` with `pnpm run generate:reference`.',
  ].join('\n');
}

/** Menu / App / Editor, in the words the reader needs, without re-telling the feature page. */
const SOURCE_LABELS = { menu: 'Menu', renderer: 'App', editor: 'Editor' };

function sourceLabel(source) {
  const label = SOURCE_LABELS[source];
  if (label === undefined) {
    throw new Error(
      `The catalogue has an accelerator source this generator does not know: \`${source}\`. ` +
        'Add it to SOURCE_LABELS in docs-site/scripts/lib/pages.mjs.'
    );
  }
  return label;
}

/** The keyboard-shortcut reference: every binding, both platforms, grouped as the app groups them. */
function shortcutsPage(sources) {
  const bound = commandRows(sources).filter(row => row.keysMac.length > 0);
  const surface = surfaceShortcutRows(sources);
  const rows = [...bound, ...surface];
  const relearn = bound.filter(row => row.differentKeyOffMac);

  const groups = byGroup(sources, rows).map(([label, groupRows]) =>
    [
      `### ${label}`,
      '',
      table(
        ['Keys (macOS)', 'Keys (Windows)', 'Command', 'What it does', 'Bound by'],
        groupRows.map(row => [
          keystrokes(row.keysMac),
          keystrokes(row.keysWindows),
          cell(row.label),
          cell(row.hint),
          sourceLabel(row.source),
        ])
      ),
    ].join('\n')
  );

  const markdown = [
    frontmatter({
      title: 'Keyboard shortcuts',
      description:
        'Every keystroke Joinery binds, on macOS and on Windows, with what binds each one.',
      order: 1,
    }),
    '',
    generatedBanner(),
    '',
    paragraph(
      `Joinery binds **${bound.length}** of its **${commandRows(sources).length}** commands to a`,
      `keystroke. With the **${surface.length}** keystrokes that belong to a surface rather than to a`,
      `command — ${surface.map(row => `_${cell(row.label)}_`).join(' and ')} — that is`,
      `**${rows.length} rows**, the same set the in-app cheat sheet shows under **⇧⌘/**.`
    ),
    '',
    // The cheat sheet this table is generated alongside. Static: the shot is a committed asset
    // (`docs-site/src/assets/screenshots/`, captured by `pnpm run docs:shots`), so it is a literal
    // here rather than anything derived from `sources` — J-99 Phase 3.
    SHOT.keyboardShortcuts,
    '',
    paragraph(
      'Every binding is listed, not only the primary one: _New connection_ answers to two menu',
      'items, and a table that showed one of them would be wrong about the other.'
    ),
    '',
    '## Reading the table',
    '',
    paragraph(
      'The **Bound by** column is the one that answers "why does this key work here but not',
      'there".'
    ),
    '',
    table(
      ['Bound by', 'What holds the keystroke'],
      [
        ['**Menu**', 'An Electron menu item. The keystroke never reaches the page at all.'],
        [
          '**App**',
          'A key listener in the window. It must avoid every registered menu accelerator.',
        ],
        [
          '**Editor**',
          'Monaco, and only while the caret is in a SQL editor. Either the menu shows the key ' +
            'without binding it, or no menu item carries it at all.',
        ],
      ]
    ),
    '',
    paragraph(
      'The [keyboard shortcuts guide](../../features/keyboard-shortcuts/) explains what follows',
      'from that, and why the snippet library is on ⌥⌘S rather than ⇧⌘S.'
    ),
    '',
    '## Every binding',
    '',
    groups.join('\n\n'),
    '',
    '## On Windows',
    '',
    paragraph(
      'Most bindings are the macOS binding with Ctrl in place of ⌘, and ⌥⌘S becomes `Ctrl+Alt+S`',
      `by the same rule. **${relearn.length}** are a different key entirely — the rows above where`,
      'the two columns name different keys rather than the same key in local modifier names.'
    ),
    '',
    callout(
      '**Note** — the Windows column is the key you press. The app writes its accelerators with',
      'the `CmdOrCtrl` modifier, which Electron resolves to Control on Windows and Linux and to',
      'Command on macOS; the in-app cheat sheet makes the same substitution when it prints a',
      'binding, so a key written `CmdOrCtrl+N` reads there as `Ctrl+N` off macOS, exactly as it',
      'does here.'
    ),
    '',
    provenance(COMMAND_SOURCES, COMMAND_MECHANISM, digest(rows)),
    '',
    claimsTable([
      [
        'Every row is derived from the command table and the surface-shortcut list',
        '`packages/renderer/src/commands/catalogue.ts:272-803`, `features/command-palette/palette-actions.ts:121-146`',
      ],
      [
        'A surface shortcut names what binds it, so ⌃M reads Editor and the palette opener reads App',
        '`packages/renderer/src/features/command-palette/palette-actions.ts:105-146`, `features/shortcuts-dialog/shortcuts-dialog.tsx:95-108`',
      ],
      [
        'The in-app cheat sheet is ⇧⌘/ and renders the same two lists',
        '`packages/renderer/src/features/shortcuts-dialog/shortcuts-dialog.tsx:69-108, 117-125`',
      ],
      [
        'A test compares these accelerators with what `menu.ts` registers',
        '`packages/renderer/src/commands/catalogue.ts:31-45`, `commands/catalogue.spec.ts`',
      ],
      [
        'Alternates are real bindings, and New connection has two',
        '`packages/renderer/src/commands/catalogue.ts:158-172, 274-283`',
      ],
      [
        'What Menu, App and Editor mean, and that App bindings must dodge menu accelerators',
        '`packages/renderer/src/commands/catalogue.ts:134-157`',
      ],
      [
        "Keystrokes are formatted by the app's own formatter, per platform",
        '`packages/renderer/src/commands/catalogue.ts:865-914`, `utils/platform.ts:18`',
      ],
      [
        'Five bindings name a different key off macOS; the sixth platform-specific one is ⌥⌘S / Ctrl+Alt+S',
        '`packages/renderer/src/commands/catalogue.ts:349, 413, 421, 574, 582` and `:639`',
      ],
      [
        'The non-macOS branch prints `Ctrl` for `CmdOrCtrl`, `CommandOrControl` and `Control`; bare `Cmd` is left alone, being macOS-only',
        '`packages/renderer/src/commands/catalogue.ts:852-863, 884-891`',
      ],
      [
        'Electron maps `CmdOrCtrl` to Command on macOS and Control elsewhere',
        '[Electron accelerator reference](https://www.electronjs.org/docs/latest/api/accelerator)',
      ],
    ]),
    '',
  ].join('\n');

  return { path: GENERATED_PAGES.shortcuts, markdown };
}

/** One command's palette cell: "Yes", "Yes — needs …", or "No — the catalogue's own reason". */
function paletteCell(palette) {
  if (!palette.inPalette) return `No — ${cell(palette.note)}`;
  return palette.note === null ? 'Yes' : `Yes — ${cell(palette.note)}`;
}

/** Each distinct reason a command is kept out of the palette, in catalogue order, with its count. */
function hiddenReasons(rows) {
  const counts = new Map();
  for (const row of rows.filter(candidate => !candidate.palette.inPalette)) {
    counts.set(row.palette.reason, (counts.get(row.palette.reason) ?? 0) + 1);
  }
  return [...counts.entries()];
}

/** The command reference: all of them, by group, with descriptions and palette availability. */
function commandsPage(sources) {
  const rows = commandRows(sources);
  const actions = paletteActionRows(sources);
  const inPalette = rows.filter(row => row.palette.inPalette);
  const withKeys = rows.filter(row => row.keysMac.length > 0);
  const reasons = hiddenReasons(rows);

  const groups = byGroup(sources, rows).map(([label, groupRows]) =>
    [
      `### ${label}`,
      '',
      table(
        ['Command', 'What it does', 'Keystroke', 'In the palette'],
        groupRows.map(row => [
          cell(row.label),
          cell(row.hint),
          keystrokes(row.keysMac),
          paletteCell(row.palette),
        ])
      ),
    ].join('\n')
  );

  const markdown = [
    frontmatter({
      title: 'Command reference',
      description:
        'Every command Joinery has, by group, with what it does, its keystroke, and whether the command palette lists it.',
      order: 2,
    }),
    '',
    generatedBanner(),
    '',
    paragraph(
      `Joinery has **${rows.length} commands** in **${byGroup(sources, rows).length} groups**.`,
      `**${inPalette.length}** of them are listed by the`,
      `[command palette](../../features/command-palette/) and **${withKeys.length}** carry a`,
      'keystroke. A command the palette does not list says so in the table below, in the words the',
      'catalogue itself uses; the full reasons are under [Not in the',
      'palette](#not-in-the-palette).'
    ),
    '',
    paragraph(
      'Keystrokes here are the macOS bindings. Both platforms are on the',
      '[keyboard shortcuts reference](../keyboard-shortcuts/).'
    ),
    '',
    '## Commands',
    '',
    groups.join('\n\n'),
    '',
    '## Not in the palette',
    '',
    paragraph(
      `**${rows.length - inPalette.length}** commands are absent from the palette, for`,
      `**${reasons.length}** reasons, each stated in the app's source beside the commands it covers.`,
      'Most of them carry a target the palette cannot supply — a palette entry is a phrase, not a',
      'node. Most of those have a target-free twin the palette offers instead; the rest are',
      'registered for surfaces that have not shipped, and have no entry point anywhere yet.'
    ),
    '',
    table(
      ['How many', 'Why the palette does not list them'],
      reasons.map(([reason, count]) => [
        count === 1 ? '1 command' : `${count} commands`,
        cell(reason),
      ])
    ),
    '',
    '## Palette-only actions',
    '',
    paragraph(
      `The palette carries **${actions.length}** entries that are not commands. Each changes one`,
      'thing in the window and needs no other surface, so it is held by the palette itself rather',
      'than dispatched through the command bus.'
    ),
    '',
    table(
      ['Action', 'What it does', 'Group'],
      actions.map(action => [cell(action.label), cell(action.hint), cell(action.groupLabel)])
    ),
    '',
    provenance(COMMAND_SOURCES, COMMAND_MECHANISM, digest({ rows, actions })),
    '',
    claimsTable([
      [
        'The command table, its groups and their order',
        '`packages/renderer/src/commands/catalogue.ts:110-133, 272-803`',
      ],
      [
        'A command that carries a payload cannot be a palette entry, and each one states why',
        '`packages/renderer/src/commands/catalogue.ts:219-270`',
      ],
      [
        'The three palette preconditions the "needs …" column reports',
        '`packages/renderer/src/commands/catalogue.ts:196-207`, `features/command-palette/palette-model.ts:98-115`',
      ],
      [
        'A row that cannot run right now is disabled with its reason, never hidden',
        '`packages/renderer/src/features/command-palette/palette-model.ts:11-25, 131-154`',
      ],
      [
        "The palette's local actions, and why they are not commands",
        '`packages/renderer/src/features/command-palette/palette-actions.ts:1-32, 72-95`',
      ],
      [
        "Theme names come from the status bar's own table, so both surfaces say Ink and Ivory",
        '`packages/renderer/src/shell/status-bar.tsx:127-134`',
      ],
    ]),
    '',
  ].join('\n');

  return { path: GENERATED_PAGES.commands, markdown };
}

/** Thousands separators, so a context window reads as a number rather than a smear of digits. */
function tokens(value) {
  return value === undefined ? '—' : value.toLocaleString('en-US');
}

/**
 * The model chat opens a new conversation on, when the user has pinned none for this vendor.
 *
 * A mirror of `packages/main/src/services/ai/chat-service.ts:46-58` — the nominated default if
 * there is one, otherwise the highest-ranked stable model among those that may be auto-selected.
 * Four of the six shipping vendors nominate nothing, so "the vendor default" is not an answer this
 * page can give for most of them, and the fallback is what a reader actually gets.
 */
function autoSelectedModel(vendor) {
  const candidates = vendor.models.filter(model => model.excludeFromAutoSelect !== true);
  if (candidates.length === 0) return null;
  const nominated = candidates.find(model => model.default === true);
  if (nominated !== undefined) return nominated;
  const stable = candidates
    .filter(model => !model.apiName.includes('preview'))
    .sort((left, right) => (right.powerRank ?? 0) - (left.powerRank ?? 0));
  return stable[0] ?? candidates[0];
}

/** What the configuration says about a model beyond its numbers. */
function modelNotes(model, chatDefault) {
  const notes = [];
  if (model.default === true) notes.push('nominated default');
  if (model === chatDefault) notes.push('chat starts here');
  if (model.excludeFromAutoSelect === true) notes.push('never auto-selected');
  if (model.supportsStreaming !== true) notes.push('no streaming');
  return notes.length === 0 ? '—' : notes.join('; ');
}

/** The AI provider and model reference, straight out of the shipped vendor configuration. */
function aiProvidersPage(vendorConfig) {
  const { version, lastUpdated, vendors } = vendorConfig;
  const modelCount = vendors.reduce((total, vendor) => total + vendor.models.length, 0);
  const keyless = vendors.filter(vendor => vendor.requiresApiKey !== true);

  const nominating = vendors.filter(vendor => vendor.models.some(model => model.default === true));

  const sections = vendors.map(vendor => {
    const chatDefault = autoSelectedModel(vendor);
    return [
      `### ${cell(vendor.name)}`,
      '',
      `API base URL: \`${cell(vendor.baseUrl)}\`` +
        (vendor.docsUrl === undefined ? '' : ` · [Get a key](${vendor.docsUrl})`),
      '',
      table(
        ['Model', 'Power rank', 'Cost tier', 'Context window', 'Max output', 'Notes'],
        vendor.models.map(model => [
          cell(model.name),
          String(model.powerRank),
          cell(model.costTier),
          tokens(model.maxContextTokens),
          tokens(model.maxOutputTokens),
          modelNotes(model, chatDefault),
        ])
      ),
    ].join('\n');
  });

  const markdown = [
    frontmatter({
      title: 'AI providers and models',
      description:
        'The vendors and models Joinery ships with, where to get a key for each, and what the configuration records about every model.',
      order: 5,
    }),
    '',
    generatedBanner(),
    '',
    paragraph(
      `Joinery ships with **${vendors.length} providers** and **${modelCount} models**, in a`,
      `configuration file the app reads at startup — version **${cell(version)}**, last updated`,
      `**${cell(lastUpdated)}**. The provider picker and the model picker are built from this list,`,
      'so neither can offer something the app cannot reach.'
    ),
    '',
    paragraph(
      keyless.length === 0
        ? 'Every provider needs an API key of your own.'
        : 'Not every provider needs an API key. Where one is needed,',
      'Joinery ships no keys and proxies nothing: the main process talks to the vendor directly',
      'from your machine, with a key you supply.'
    ),
    '',
    callout(
      "**Note** — the key goes to the operating system's credential store, never to a file in the",
      'profile. [AI setup](../../features/ai-setup/) walks through adding one, and',
      '[Prerequisites](../../getting-started/prerequisites/#where-credentials-go) says where',
      'credentials live.'
    ),
    '',
    '## What the columns mean',
    '',
    table(
      ['Column', 'Meaning'],
      [
        [
          'Power rank',
          '1–20, higher is more capable. Joinery matches this number when it picks a model for a non-chat AI feature.',
        ],
        [
          'Cost tier',
          'The band the configuration files the model under. It is a property of the file, not a price Joinery observes.',
        ],
        ['Context window', 'Maximum input tokens, as the configuration records them.'],
        ['Max output', 'Maximum tokens in one reply, as the configuration records them.'],
        [
          'Notes',
          '_Nominated default_ is a flag in the file. _Chat starts here_ is the model a new conversation actually opens on. _Never auto-selected_ marks the routers, whose capability is whatever they route to.',
        ],
      ]
    ),
    '',
    paragraph(
      'The two default notes are not the same thing, and most vendors show only the second.',
      `**${nominating.length}** of the **${vendors.length}** nominate a default model in the file.`,
      'For the rest, a conversation you have not pinned a model for opens on the **highest-ranked',
      'stable model** the vendor offers — preview models lose to a stable sibling, and routers are',
      'not eligible at all. Either way you can pin a preferred model per provider in AI setup, and',
      'override it for a single message in the composer.'
    ),
    '',
    paragraph(
      'The model picker in AI setup lists model names only; the numbers here are what the shipped',
      'configuration records behind them.'
    ),
    '',
    SHOT.aiSetup,
    '',
    '## Providers',
    '',
    sections.join('\n\n'),
    '',
    provenance([VENDOR_SOURCE], VENDOR_MECHANISM, digest(vendorConfig)),
    '',
    claimsTable([
      ['The vendors, models, versions and key links', `\`${VENDOR_SOURCE}\``],
      [
        'Power rank is 1–20, higher is more capable, and drives automatic model selection',
        '`packages/shared/src/types/ai.types.ts:60-82`, `packages/main/src/services/ai/ai-service.ts:337-346`',
      ],
      [
        'Router models are excluded from automatic selection because their rank is whatever they route to',
        '`packages/shared/src/types/ai.types.ts:75-81`, `packages/main/src/services/ai/ai-service.ts:335-339`',
      ],
      [
        'Chat opens on the nominated default, else the highest-ranked stable auto-selectable model',
        '`packages/main/src/services/ai/chat-service.ts:35-58`',
      ],
      [
        'Four of the six vendors nominate no default, so the fallback is the usual path',
        '`packages/shared/src/config/ai-vendors.json`, `packages/main/src/services/ai/chat-service.ts:38-41`',
      ],
      [
        'A preferred model can be pinned per provider, and overridden for one message',
        '`packages/renderer/src/features/ai-setup/ai-setup-dialog.tsx:315-325`, `features/chat/chat-composer.tsx:272-320`',
      ],
      [
        'The AI setup dialog lists the vendors and models from this file, showing model names',
        '`packages/renderer/src/features/ai-setup/ai-setup-dialog.tsx:225-233, 315-325`',
      ],
      [
        'Keys are held by the OS credential store through `keytar`, per vendor',
        '`packages/main/src/services/keychain/credential-store.ts:1-14`, `services/ai/ai-service.ts:136-138`',
      ],
    ]),
    '',
  ].join('\n');

  return { path: GENERATED_PAGES.aiProviders, markdown };
}

/** The three pages, as `{ path, markdown }` — the same values the writer and the checker use. */
export function buildPages({ sources, vendorConfig }) {
  return [shortcutsPage(sources), commandsPage(sources), aiProvidersPage(vendorConfig)];
}
